const Home = () => {
    return(
        // </>
        // <h1>HOME</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis deleniti, itaque, ullam cupiditate nihil cumque enim libero quia praesentium veritatis modi sunt nesciunt veniam. Corrupti sunt perferendis reiciendis vel rerum hic provident illo totam, dolor aliquid qui optio doloremque. Voluptas illum obcaecati quis, mollitia culpa consectetur aut consequatur incidunt eum eveniet repellat ullam delectus aliquid unde id. Sequi, aut. Provident repellat repudiandae officia dicta modi facere ipsum voluptate voluptatem itaque voluptatum corporis aliquam quia reiciendis veniam, molestias nam non. Minima officia animi nulla perferendis. Voluptates molestias iure consectetur unde quae ex rerum magni laudantium, neque minima quis laboriosam a vel dolores, suscipit itaque! Dolores ab, provident delectus ducimus excepturi, quia perferendis eligendi, quisquam sit tempore sequi ipsum dolore ullam ut exercitationem natus! Sequi ipsam neque voluptatem dicta, expedita accusantium fugit optio nobis eum dolorum repellat! Mollitia architecto quos enim sit. At quam ullam ex explicabo voluptatem corporis ea similique est eius? Blanditiis nostrum at placeat possimus est voluptatum cum error dignissimos recusandae harum, doloremque animi eum maxime reprehenderit nobis, vero ipsum pariatur laborum minima ea? Obcaecati illo nisi cupiditate! Voluptas, error possimus nesciunt perferendis tempore ipsam id debitis laboriosam illum quasi dolores, voluptate labore quibusdam, quis magni nihil molestiae. Quam sit debitis aut veniam quo voluptatibus magnam, quidem dicta omnis laborum aperiam rerum, corporis reprehenderit, temporibus excepturi nesciunt doloribus porro nam dolorem expedita fuga repudiandae eligendi modi labore! Iusto saepe cupiditate quaerat facere quam, beatae, ducimus quas dolores modi neque consequuntur fugiat repellendus? Optio aut soluta, dolorem ducimus quis, accusamus eius magnam reprehenderit pariatur facilis, eum consectetur. Odio dicta beatae dolores reprehenderit tempora natus optio odit. Voluptates hic enim ipsam atque rem repudiandae omnis itaque ut neque, veritatis amet numquam animi ratione consequuntur eum quo, ipsum aliquam nam. Quasi reprehenderit consequatur quisquam, reiciendis quas veniam in similique adipisci deserunt expedita distinctio, officiis provident tempora modi quae asperiores, dolore doloremque! Mollitia, saepe dolore? Aliquam assumenda, quod iste quam ex iure impedit alias aperiam tempore cum eaque facilis adipisci aut error mollitia modi voluptatum consequatur dignissimos repudiandae provident commodi omnis, quos quo! Et voluptate cumque officia iure, id eveniet earum tempore unde sint minus corporis a amet!</p>
        // </>
    )
}

export default Home